# Nome da Aplicação
spring.application.name=meu-rumo-financeiro

# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:meurumodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 (Para você visualizar o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL no console (Ótimo para aprender o que o Hibernate está fazendo)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update