# Nome da Aplicação
spring.application.name=financeiro-api-backend

# Configurações de Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/meurumo_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=user_meurumo
spring.datasource.password=password_meurumo

# Configurações do Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect